### ISSUE TITLE
How to implement

### ISSUE THREAD

**Issue by Disillusioned** [sympthom/M-Bus#1]
How do I implement this & execute a test TCP MBUS read using this library?

**Comment by sympthom** [comment]
Hi,

Thanks for your comments.

During the development phase I've been using a Pigaab 900S (https://www.piigab.com/produkter/hardware/piigab-m-bus-900) as a collector/gateway and a wm-bus watermeter from b meters (http://www.bmeters.se). The water meter registers itself within the collector/gateway through wm-bus. Then target the tcp binding towards the collector/gateway.

You should be able to target any m-bus collector/gateway that exposes it's m-bus protocol over tcp.

Regards,
Martin

**Comment by sympthom** [comment]
A read for data on a particular meter address can be done like this:
```     
var endpoint = new UdpEndpointBinding(new IPEndPoint(IPAddress.Parse("192.168.1.135"), 502), new FrameSerializer(), new Logger());

var response = await new MBusMaster(endpoint)
                .RequestData2(0x0a, TimeSpan.FromSeconds(3));
```
